# Generated by Django 4.2.3 on 2023-08-02 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='descripttion',
            new_name='description',
        ),
    ]
